### ISSUE TITLE
Can not connect to the Wii

### ISSUE THREAD

**Issue by skadge** [rnconrad/WiimoteEmulator#2]
Issue #1 being now solved, I tried without success to connect to the Wii.
I get:

```
 $ ./wmemulator A4:C0:E1:87:92:A4
connecting to A4:C0:E1:87:92:A4 psm 17
can't connect to A4:C0:E1:87:92:A4 psm 17
cleaning up...
```

The actual error (printed with `strerror(errno)`) is `Permission denied` (on subsequent attempts, we get instead `Connection reset by peer`).

I'm pretty sure that BT address of the is correct, because if I want to re-use the WiiMote, I first need to resync it with the Wii, which seems to indicate that the Wii lost trust in the WiiMote/WiiMote emulator.

Any thoughts?

**Comment by severin-lemaignan** [comment]
I've recorded the bluetooth connection attempt with wireshark:

![wii-bt-log](https://cloud.githubusercontent.com/assets/385379/19384682/5e9fda28-9202-11e6-9822-6a973d5fb0af.png)

Apparently, the Wii is expecting a PIN or Link key, and does not get them...

**Comment by severin-lemaignan** [comment]
`hcidump`:

```
$ hcidump
HCI sniffer - Bluetooth packet analyzer ver 5.37
device: hci0 snap_len: 1500 filter: 0xffffffffffffffff
> HCI Event: Command Status (0x0f) plen 4
    Create Connection (0x01|0x0005) status 0x00 ncmd 1
> HCI Event: Connect Complete (0x03) plen 11
    status 0x00 handle 12 bdaddr A4:C0:E1:87:92:A4 type ACL encrypt 0x00
> HCI Event: Command Status (0x0f) plen 4
    Read Remote Supported Features (0x01|0x001b) status 0x00 ncmd 1
> HCI Event: Read Remote Supported Features (0x0b) plen 11
    status 0x00 handle 12
    Features: 0xff 0xff 0x8d 0xfe 0x9b 0xf9 0x00 0x80
> HCI Event: Command Status (0x0f) plen 4
    Read Remote Extended Features (0x01|0x001c) status 0x00 ncmd 1
> HCI Event: Read Remote Extended Features (0x23) plen 13
    status 0x00 handle 12 page 1 max 0
    Features: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
> HCI Event: Command Status (0x0f) plen 4
    Remote Name Request (0x01|0x0019) status 0x00 ncmd 1
> HCI Event: Remote Name Req Complete (0x07) plen 255
    status 0x00 bdaddr A4:C0:E1:87:92:A4 name 'Wii'
> HCI Event: Command Complete (0x0e) plen 10
    Link Key Request Negative Reply (0x01|0x000c) ncmd 1
    status 0x00 bdaddr A4:C0:E1:87:92:A4
> HCI Event: Command Complete (0x0e) plen 10
    PIN Code Request Negative Reply (0x01|0x000e) ncmd 1
    status 0x00 bdaddr A4:C0:E1:87:92:A4
> HCI Event: Disconn Complete (0x05) plen 4
    status 0x00 handle 12 reason 0x05
    Reason: Authentication Failure
```

**Comment by rnconrad** [comment]
The bluez plugin handles the PIN authentication so this is almost certainly where the problem is. The readme is pretty vague about this so I'll explain the process in more detail.

I am still looking for a better solution, but without requiring a custom build of bluez, it seems that a simple dynamically linked plugin for bluez 4.101 is the easiest way to get it working. Newer versions of bluez will not work because the plugin's PIN callback is no longer invoked unless the devices are bonding (in this case they are not, the Wii just asks for a password when connecting).

So you'll need to compile and install bluez 4.101. You don't need to compile it if the correct version is already installed, but you'll need the source to compile the plugin. If you already have a newer version installed, then install bluez 4.101 alongside the original. To compile and install bluez:

```
> ./configure <options if needed>
> make
> sudo make install
```

To check bluez version:

```
> bluetoothd --version
```

If you already had bluez installed, make sure to stop it:

```
> sudo service bluetooth stop
```

and/or 

```
> sudo killall bluetoothd
```

Once bluez 4.101 is installed, copy the contents of the bluez-plugin directory to the plugins source folder `bluez-4.101/plugins` and run `make`. Copy the output `wmemu.so` file to the bluez installation's plugins directory. This is usually `/usr/lib/bluetooth/plugins` but depends on how the installation was configured. It is possible to determine this location along with whether or not the plugin loaded properly by starting bluez (make sure to stop any running versions first) with:

```
> sudo bluetoothd -n -d
```

A debug message from `src/plugin.c:plugin_init()` will print the plugin directory and messages following it should indicate that the wmemu plugin was loaded (with no errors). Anything abnormal here could indicate what the problem is.

This is admittedly a convoluted process for PIN authentication, but because the Wii requires a PIN that cannot always be represented as a string, simpler methods (e.g. the bluez dbus interface) will not work.

**Comment by skadge** [comment]
Thank you very much @rnconrad for the detailed explanations! This indeed allowed me to successfully connect to the Wii. I guess we should add these steps to the README.

Closing this issue now.
